version: 2.1
jobs:
  failure_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run:
         name: on error
         command: echo "Hello Error!"
         when: on_fail
workflows:
  my_workflow:
    jobs:
      - failure_test


